'use client'

import { useEffect, useState } from 'react'
import Image from 'next/image'
import { ArrowUpRight, ChevronLeft, ChevronRight, Menu, X, Play, Plus } from 'lucide-react'

const projects = [
  { title: 'Nexo Operations', type: 'PLATAFORMA / OPERACIONES', text: 'Un nuevo centro de control para equipos que necesitan ver, decidir y actuar en tiempo real.', image: '/axyso-project-1.png', stat: '−42% tiempo operativo' },
  { title: 'Luma Intelligence', type: 'PRODUCTO / IA', text: 'Una experiencia inteligente que convierte datos complejos en decisiones humanas.', image: '/axyso-project-2.png', stat: '+3.4x adopción' },
  { title: 'Atelier Cloud', type: 'ECOSISTEMA / WEB', text: 'Una presencia digital viva para una marca que no quería parecerse a ninguna otra.', image: '/axyso-hero.png', stat: '+186% conversión' },
]
const services = ['Software a medida', 'Sistemas de IA', 'Experiencias web', 'Productos SaaS']

function useReveal() { useEffect(() => { const els = document.querySelectorAll('.reveal'); const io = new IntersectionObserver(es => es.forEach(e => { if (e.isIntersecting) { e.target.classList.add('is-visible'); io.unobserve(e.target) } }), { threshold: .12 }); els.forEach(e => io.observe(e)); return () => io.disconnect() }, []) }
function Brand() { return <a href="#inicio" className="brand">AXYSO<span>.</span></a> }
function Header() { const [open, setOpen] = useState(false); const links = [['Índice','#inicio'],['Servicios','#servicios'],['Proyectos','#proyectos'],['Estudio','#estudio']]; return <header className="site-header"><div className="header-inner"><Brand /><nav className="desktop-nav">{links.map(([l,h])=><a key={l} href={h}>{l}</a>)}</nav><a className="header-cta" href="#contacto">Hablemos <ArrowUpRight size={15}/></a><button className="menu-button" onClick={()=>setOpen(!open)} aria-label="Abrir menú">{open?<X/>:<Menu/>}</button></div>{open&&<nav className="mobile-nav">{links.map(([l,h])=><a key={l} href={h} onClick={()=>setOpen(false)}>{l}</a>)}<a href="#contacto" onClick={()=>setOpen(false)}>Hablemos <ArrowUpRight size={15}/></a></nav>}</header> }
function Hero() { return <section className="hero" id="inicio"><div className="hero-copy"><p className="eyebrow">AXYSO / ESTUDIO DIGITAL <span>2026</span></p><h1>Hacemos que lo <em>complejo</em> se sienta simple.</h1><p className="hero-lead">Diseñamos sistemas, productos y experiencias digitales para organizaciones que están construyendo lo siguiente.</p><div className="hero-actions"><a className="button button-primary" href="#proyectos">Ver proyectos <ArrowUpRight size={17}/></a><button className="play-link"><span><Play size={12} fill="currentColor"/></span> Conoce AXYSO</button></div></div><div className="hero-visual"><Image src="/axyso-hero.png" alt="Interfaz abstracta de un sistema digital" fill priority sizes="(max-width: 800px) 100vw, 50vw"/><div className="visual-caption"><span>FIG. 01 — SYSTEM / EMERGING</span><span>SCROLL TO EXPLORE ↓</span></div><div className="visual-index">A<span>01</span></div></div></section> }
function Marquee() { return <div className="marquee"><div>STRATEGY <i>✳</i> DESIGN <i>✳</i> ENGINEERING <i>✳</i> INTELLIGENCE <i>✳</i> STRATEGY <i>✳</i> DESIGN <i>✳</i> ENGINEERING <i>✳</i></div></div> }
function Intro() { return <section className="intro section-pad reveal" id="estudio"><div className="intro-aside"><span className="eyebrow">01 / EL ESTUDIO</span><span className="vertical-note">SCROLLING THROUGH IDEAS ↘</span></div><div><h2>Un estudio para las ideas que todavía <em>no tienen nombre.</em></h2><p>AXYSO es un estudio independiente de software y diseño digital. Trabajamos en la intersección entre estrategia, tecnología y cultura para dar forma a productos con un punto de vista.</p><a className="text-link" href="#contacto">Conoce nuestra forma de trabajar <ArrowUpRight size={16}/></a></div></section> }
function Services() { const [active,setActive]=useState(0); return <section className="services section-pad reveal" id="servicios"><div className="section-kicker"><span>02 / CAPACIDADES</span><span>SELECTED SERVICES</span></div><div className="services-layout"><div className="service-tabs">{services.map((s,i)=><button className={active===i?'active':''} key={s} onClick={()=>setActive(i)}><span>0{i+1}</span>{s}<ArrowUpRight size={17}/></button>)}</div><div className="service-detail"><p className="eyebrow">CAPACIDAD 0{active+1}</p><h2>{services[active]}<em>.</em></h2><p>Convertimos retos difíciles en sistemas claros, útiles y preparados para evolucionar. Desde la primera conversación hasta el último pixel, todo está pensado para mover las cosas hacia adelante.</p><div className="detail-metric"><strong>{['∞','24/7','3×','100%'][active]}</strong><span>{['posibilidades para explorar','pensamiento en movimiento','más claridad en cada decisión','hecho alrededor de personas'][active]}</span></div></div></div></section> }
function Projects() { const [active,setActive]=useState(0); const p=projects[active]; return <section className="projects section-pad reveal" id="proyectos"><div className="section-kicker"><span>03 / CASOS</span><span>SELECTED WORK / {String(active+1).padStart(2,'0')} — 03</span></div><div className="project-carousel"><div className="project-image"><Image src={p.image} alt={p.title} fill sizes="(max-width: 800px) 100vw, 55vw"/><span className="project-number">0{active+1}</span></div><div className="project-info"><p className="eyebrow">{p.type}</p><h2>{p.title}<em>.</em></h2><p>{p.text}</p><div className="project-stat"><strong>{p.stat.split(' ')[0]}</strong><span>{p.stat.substring(p.stat.indexOf(' ')+1)}</span></div><a className="text-link" href="#contacto">Ver caso <ArrowUpRight size={16}/></a><div className="carousel-controls"><button onClick={()=>setActive((active+projects.length-1)%projects.length)} aria-label="Proyecto anterior"><ChevronLeft/></button><button onClick={()=>setActive((active+1)%projects.length)} aria-label="Siguiente proyecto"><ChevronRight/></button><div className="carousel-dots">{projects.map((_,i)=><button key={i} className={active===i?'active':''} onClick={()=>setActive(i)} aria-label={`Ir al proyecto ${i+1}`}/>)}</div></div></div></div></section> }
function Workflow() { return <section className="workflow section-pad reveal"><div className="section-kicker"><span>04 / MÉTODO</span><span>FROM QUESTION TO MOMENTUM</span></div><h2>Las buenas ideas no aparecen.<br/><em>Se ponen en movimiento.</em></h2><div className="workflow-track">{[['01','Pregunta','Encontramos la pregunta que vale la pena responder.'],['02','Señal','Buscamos patrones donde otros solo ven ruido.'],['03','Forma','Damos forma a una respuesta que se pueda usar.'],['04','Impulso','Lanzamos, medimos y volvemos a empezar.']].map(([n,t,d])=><div className="workflow-step" key={n}><span>{n}</span><div className="step-line"/><h3>{t}</h3><p>{d}</p></div>)}</div></section> }
function Contact() { return <section className="contact section-pad reveal" id="contacto"><div><p className="eyebrow">05 / SIGUIENTE</p><h2>¿Qué podemos<br/><em>hacer posible?</em></h2></div><div><p>Cuéntanos dónde estás y hacia dónde quieres ir. Abrimos una conversación, no un formulario.</p><a className="button button-light" href="mailto:hola@axyso.com">Iniciar conversación <ArrowUpRight size={17}/></a></div></section> }
function Footer() { return <footer className="footer section-pad"><Brand/><div className="footer-bottom"><span>© 2026 AXYSO — Software & Digital Products</span><span>Buenos Aires / Remoto</span></div></footer> }
export function AxysoLanding() { useReveal(); return <><Header/><main><Hero/><Marquee/><Intro/><Services/><Projects/><Workflow/><Contact/></main><Footer/></> }
